#!/bin/bash

#
# @author Tomas Henzl (tomas.henzl@webglobe.com)
#
# changelog:
#   2024/08/27 - added check for cgi-fcgi binary
#   2022/07/21 - created
#

function die() { echo "$1" 1>&2; exit "${2:-1}"; }

# check required binary is pressent
command -v 'cgi-fcgi' &> /dev/null || die 'cgi-fcgi binary not found, please install: libfcgi-bin' 3

#
# lets get data from each socket:uri
#

for fpm_connection_info in "$@"; do
    IFS=: read socket uri <<< "$fpm_connection_info"

    _result=$(
        SCRIPT_NAME="$uri" \
        SCRIPT_FILENAME="$uri" \
        REQUEST_METHOD=GET \
        cgi-fcgi -bind -connect "${socket// /:}" 2>/dev/null
    )

    result_rets+=( $? )
    result_values+=( "$_result" )
    result_sockets+=( "$socket" )
    result_uris+=( "$uri" )
done


#
# parse performace data
#

for (( i=0; i < ${#result_values[@]}; i++ )); do
	socket="${result_sockets[$i]}"
	socket="${socket##*/}"			# remove leading path
	socket="${socket%.sock*}"		# remove any ".sock" at the end

	sockets_pretty+=( "$socket" )

    while IFS=: read name value; do
        [[ -z "$value" ]] && continue

        value="${value// /}"
#        echo "$name - $value"

        case "$name" in
            'idle processes')       performace_data+=" ${socket}_idle_procs=${value:-0}";;
            'active processes')     performace_data+=" ${socket}_active_procs=${value:-0}"; pools_active_procs+=( $value );;
            'total processes')      performace_data+=" ${socket}_total_procs=${value:-0}";;
            'max active processes') performace_data+=" ${socket}_max_active_procs=${value:-0}";;
        esac
    done <<< "${result_values[$i]}"

    # some socket did not return zero, hard error
    if [[  "${result_rets[$i]}" != "0" ]]; then
        msg_status='CRITICAL'
        msg_details="${result_sockets[$i]}:${result_uris[$i]} command returned non zero"
        ret=2
    fi

    # some socket did not provided data, hard error
    if [[ -z "${result_values[$i]}" ]]; then
        msg_status='CRITICAL'
        msg_details+="; ${result_sockets[$i]}:${result_uris[$i]} returned invalid value"
        ret=2
    fi
done

#
# print all info
#

echo -n "${msg_status:-OK}: "

# exit immediatelly on this error
[[ -n "$msg_details" ]] && die "$msg_details" "$ret"

# or print status & performace_data
echo -n "All pools running: "
for (( i=0; i < ${#sockets_pretty[@]}; i++ )); do
    echo -n "${sockets_pretty[$i]} (${pools_active_procs[$i]} working)"

    (( i+1 < ${#sockets_pretty[@]} )) && echo -n ', '
done

echo "|$performace_data"

