#!/bin/bash

#
# @author Tomas Henzl (tomas.henzl@webglobe.com)
#
# changelog:
#   2023/10/10 - created
#
# https://wiki.webglobe.com/Icinga#https_check
#

for https_host_entry in "$@"; do
    IFS=: read host warn crit <<< "$https_host_entry"

	result+=( "$(/usr/lib64/nagios/plugins/check_http --sni -H "$host" -C "${warn:-5}","${crit:-3}" 2>&1)" )
	ret=$?
	(( ret > ret_max )) && ret_max=$ret
done

printf "%s<br>" "${result[@]}"
echo

exit "${ret_max:-0}"
