#!/bin/bash

#
# @author Tomas Henzl (tomas.henzl@webglobe.com)
#
# changelog:
#   2024/09/06 - added support for note
#   2023/10/20 - show host in output (yes, it's needed)
#   2023/10/10 - created
#
# https://wiki.webglobe.com/Icinga#https_check
#

for https_host_entry in "$@"; do
    IFS=: read host warn crit note <<< "$https_host_entry"

	[[ -n "$note" ]] && note_f=" (${note})"
	result+=( "${host}${note_f}: $(/usr/lib64/nagios/plugins/check_http --sni -H "$host" -C "${warn:-4}","${crit:-2}" 2>&1)" )
	ret=$?
	(( ret > ret_max )) && ret_max=$ret
done

printf "%s<br>" "${result[@]}"
echo

exit "${ret_max:-0}"
