#!/bin/bash

cm_expect=$1
cs_expect=$2

if [ "$cm_expect" == "" ]; then
  cm_expect=0
fi

if [ "$cs_expect" == "" ]; then
  cs_expect=0
fi

cm_n=$(keydb-cli info replication | grep connected_masters: | awk -F ":" '{ print $2 }' | tr -d '\n' | tr -d '\r')
cs_n=$(keydb-cli info replication | grep connected_slaves: | awk -F ":" '{ print $2 }' | tr -d '\n' | tr -d '\r')

rt=0
if [ "$cm_n" != "$cm_expect" ]; then
  echo "connected_masters:$cm_n, expected $cm_expect"
  rt=2
else
  echo -e "connected_masters:$cm_n - OK"
fi

if [ "$cs_n" != "$cs_expect" ]; then
  echo "connected_slaves:$cs_n, expected $cs_expect"
  rt=2
else
  echo -e "connected_slaves:$cs_n - OK"
fi

exit $rt
